# Generated by Django 5.2 on 2025-06-15 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_convocatoria', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumnos_con_acceso', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'student'}, related_name='oposiciones_acceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Oposiciones',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumnos_con_acceso', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'student'}, related_name='temas_acceso', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
