# Generated by Django 5.0.14 on 2025-07-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaexamentest',
            name='penalizada_por_pausa',
            field=models.BooleanField(default=False, help_text='Si la pregunta fue marcada como incorrecta por pausar el examen'),
        ),
    ]
