# Generated by Django 5.0.14 on 2025-07-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_penalizada_por_pausa_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='examentestresultado',
            name='examen_signature',
            field=models.CharField(blank=True, help_text='Hash de los temas y apartados seleccionados para identificar exámenes similares', max_length=500),
        ),
    ]
