# Generated by Django 5.2.4 on 2025-07-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_pregunta_respuesta_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='respuesta',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='dificultad',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='puntos',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='orden',
        ),
    ]
