# Generated by Django 5.2.4 on 2025-07-16 17:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del usuario', null=True, upload_to=accounts.models.user_profile_picture_path),
        ),
    ]
